name: Windows CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 6 * * 1"

jobs:
  specs:
    name: Specs
    runs-on: windows-latest

    steps:
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
      - name: Checkout source code
        uses: actions/checkout@v2  
      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
      - name: Compile Monocypher
        shell: cmd
        run: |
            cd ext
            cl /c /EHsc /O2 /MT monocypher.c 
            cl /c /EHsc /O2 /MT monocypher-ed25519.c
            lib monocypher.obj monocypher-ed25519.obj
            copy monocypher.lib D:\a\_temp\crystal-nightly-true-undefined\lib
      - name: Run specs
        run: crystal spec --error-on-warnings --error-trace
